import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/(header)/Navbar";
import Footer from "@/components/Footer";
import Bulten from "@/components/(header)/Bulten";
import Content from "@/components/Content";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>İstib Haber</title>
        <meta name="description" content="Generated by istib Bilgi İşlem" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <Bulten/>
        <Navbar />
        <div className="container">
       
        <Content/>
        <Footer />
        </div>
        
      </div>
    </>
  );
}



